# Generated by Django 6.0.3 on 2026-05-03 22:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0002_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="social_notif_recipient_created",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="social_noti_recipie_ae546a_idx",
            old_name="social_notif_recipient_read",
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-created_at"],
                name="social_noti_recipie_54eb87_idx",
            ),
        ),
    ]
